    https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [ ]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(100000)
my_list = list(range(1000000))


In [ ]:
%time

for _ in range(10):
    #lsit的comprehension, list綜表達式
    my_lists = [x*2 for x in my_list]
    

In [ ]:
%time for _ in range(10): my_array2 = my_array *2

In [ ]:
#tuple,1個元素的表示法
(4,5)
type((4, ))


In [ ]:
np.array(range(4)).shape



### 50個學生,每個學生有5個分數,每個分數50~100

In [ ]:
#1
scores = np.random.randint(50, 101, (50,5))
scores

In [ ]:
#2
np.random.seed(42)
scores = np.random.randint(50, 101, (50,5))
scores

In [ ]:
#ndarry常用的實體屬性
scores.ndim
scores.shape
scores.size
scores.dtype

### 基本索引和分割
- ndarray[index]
- ndarray[Start:end:Stop]

In [ ]:
#2維
scores[0][4] #類似list的操作
scores[0, 4] #ndarrya的slice的操作法

In [ ]:
## 取的第1位學生的分數
scores[0] #shape(5, )
scores[0,:] #shape(5,0)
scores[0:1,:] #shape(1,5)


In [25]:
## 取的第1,2位學生的分數
scores[:2] 
scores[:2,:] 
scores[(0,1),:]


array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60]], dtype=int32)

In [26]:
## 取得第1,2,5位學生的分數
scores[(0,1,4),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [79, 87, 51, 70, 82]], dtype=int32)

In [ ]:
## 取得第1科的所有分數
scores[:,0] #(50,)
scores[:,0:1] #(1,50)

In [ ]:
## 取得第1,2科的所有分數
scores[:,:2] #(50,2)

In [ ]:
## 取得前30位學生的最後3科分數
scores[:30,-3:] #(30,3)

### ndarry的統計的實體方法
- sum()
- min()
- max()
- mean()

In [27]:
# 每個學生的總分和平均
scores.sum(axis=1)

array([379, 358, 380, 340, 369, 397, 373, 427, 372, 356, 330, 398, 397,
       339, 366, 370, 353, 385, 412, 376, 311, 383, 373, 400, 315, 410,
       413, 400, 294, 349, 392, 401, 419, 381, 385, 368, 411, 381, 330,
       334, 452, 372, 435, 385, 343, 371, 368, 315, 352, 375])

In [ ]:
#每個學生的總分
scores.sum(axis=1) #ndarray實體方法

np.sum(scores,axis=1) #numpy的global的function

In [ ]:
# 前30為學生的平均
scores[:30].mean(axis=1)

In [28]:
# 第1科最高的分數和最低分數
scores[:,0].max(axis=0)
scores[:,0].min(axis=0)

np.int32(50)