    https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [ ]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(100000)
my_list = list(range(1000000))

my_list


In [ ]:
%time                                               #a魔術運算值 只有 ipynb檔能用

for _ in range(10):
    #lsit的comprehension, list綜合表達式
    my_lists = [x*2 for x in my_list]
    

In [ ]:
%time for _ in range(10): my_array2 = my_array *2

In [ ]:
#tuple,1個元素的表示法
(4,5)
type((4, ))


In [ ]:
np.array(range(4)).shape



### 50個學生,每個學生有5個分數,每個分數50~100

In [ ]:
#1
scores = np.random.randint(50, 101, (50,5))             #五十分到一百分隨機取  
scores

In [17]:
#2
np.random.seed(42)                                      #
scores = np.random.randint(50, 101, (50,5))
scores

array([[ 88,  78,  64,  92,  57],
       [ 70,  88,  68,  72,  60],
       [ 60,  73,  85,  89,  73],
       [ 52,  71,  51,  73,  93],
       [ 79,  87,  51,  70,  82],
       [ 61,  71,  93,  74,  98],
       [ 76,  91,  77,  65,  64],
       [ 96, 100,  93,  52,  86],
       [100,  56,  70,  58,  88],
       [ 67,  53,  74,  63,  99],
       [ 58,  75,  51,  69,  77],
       [ 96,  56,  93,  57,  96],
       [ 84,  63,  66,  85,  99],
       [ 89,  53,  51,  55,  91],
       [ 53,  78,  67,  75,  93],
       [ 83,  59,  85,  63,  80],
       [ 97,  64,  57,  63,  72],
       [ 89,  70,  65,  94,  67],
       [ 96,  73,  75,  74,  94],
       [ 90,  78,  64,  94,  50],
       [ 74,  56,  58,  73,  50],
       [ 93,  57,  73,  60, 100],
       [ 66,  57,  84,  84,  82],
       [ 54,  91,  88,  90,  77],
       [ 56,  58,  57,  61,  83],
       [ 82,  97,  72,  73,  86],
       [ 84,  93,  89,  71,  76],
       [ 84,  50,  84,  86,  96],
       [ 63,  52,  50,  54,  75],
       [ 63,  

In [ ]:
#ndarry常用的實體屬性
scores.ndim
scores.shape
scores.size
scores.dtype

### 基本索引(index)和分割(slicing)
- ndarray[index]
- ndarray[Start:end:Stop]

In [19]:
#2維
scores[0][4] #類似list的操作
scores[0, 4] #ndarrya的slice的操作法

np.int32(57)

In [ ]:
## 取的第1位學生的分數
scores[0] #shape(5, )
scores[0,:] #shape(5,0)
scores[0:1,:] #shape(1,5)               #start:end:step     用二維表示


array([[88, 78, 64, 92, 57]], dtype=int32)

In [ ]:
## 取的第1,2位學生的分數
scores[:2]                              #第一維使用slicing  
scores[:2,:] 
scores[(0,1),:]


array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60]], dtype=int32)

In [ ]:
## 取得第1,2,5位學生的分數
scores[(0,1,4),:]
# scores[0:5,:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [60, 73, 85, 89, 73],
       [52, 71, 51, 73, 93],
       [79, 87, 51, 70, 82]], dtype=int32)

In [ ]:
## 取得第1科的所有分數
scores[:,0] #(50,)
scores[:,0:1] #(1,50)

In [ ]:
## 取得第1,2科的所有分數
scores[:,:2] #(50,2)

In [ ]:
## 取得前30位學生的最後3科分數
scores[:30,-3:] #(30,3)

### ndarry的統計的實體方法
- sum()
- min()
- max()
- mean()

In [32]:
# 每個科的總分
scores.sum(axis=0)

array([3717, 3670, 3756, 3647, 3905])

In [33]:
#每個學生的總分
scores.sum(axis=1) #ndarray實體方法

np.sum(scores,axis=1) #numpy的global的function

array([379, 358, 380, 340, 369, 397, 373, 427, 372, 356, 330, 398, 397,
       339, 366, 370, 353, 385, 412, 376, 311, 383, 373, 400, 315, 410,
       413, 400, 294, 349, 392, 401, 419, 381, 385, 368, 411, 381, 330,
       334, 452, 372, 435, 385, 343, 371, 368, 315, 352, 375])

In [34]:
# 前30為學生的平均
scores[:30].mean(axis=1)

array([75.8, 71.6, 76. , 68. , 73.8, 79.4, 74.6, 85.4, 74.4, 71.2, 66. ,
       79.6, 79.4, 67.8, 73.2, 74. , 70.6, 77. , 82.4, 75.2, 62.2, 76.6,
       74.6, 80. , 63. , 82. , 82.6, 80. , 58.8, 69.8])

In [ ]:
# 第1科最高的分數和最低分數
scores[:,0].max(axis=0)
scores[:,0].min(axis=0)

np.int32(50)