### numpy的reshape()
https://www.perplexity.ai/search/8fe65bd5-dbd8-45b1-8f50-8351f5dcbd9d

In [6]:
import numpy as np

array = np.arange(12)
array.shape

(12,)

In [17]:
array1 = array.reshape((3, 4))
array1.shape
print(array1)
array1[1,2]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(6)

In [16]:
array2 = array1.reshape((2, 6))
print(array2)
array2[1,0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


np.int64(6)

In [19]:
array3 = array2.reshape((1, 2, 1, 6, 1))
print(array3)
array3[0,1,0,0,0]

[[[[[ 0]
    [ 1]
    [ 2]
    [ 3]
    [ 4]
    [ 5]]]


  [[[ 6]
    [ 7]
    [ 8]
    [ 9]
    [10]
    [11]]]]]


np.int64(6)